// app/src/pages/results/league/Index.vue
<template>
  <div>
    <h1>関東学生バドミントン連盟リーグ</h1>
    <div class="table-responsive mt-5">
      <table class="table table-bordered">
        <thead class="bg-light">
          <tr>
            <th class="font-weight-normal" colspan="2">期</th>
            <th class="font-weight-normal">男子</th>
            <th class="font-weight-normal">女子</th>
          </tr>
        </thead>
        <tbody>
          <template v-for="(year, i) in leagueResults">
            <tr v-for="(season, j) in year.season" :key="i + '-' + j">
              <th
                class="font-weight-normal bg-light align-middle"
                v-if="j === 0"
                :rowspan="year.season.length"
              >{{ year.year }}</th>
              <th class="font-weight-normal bg-light">{{ season.season }}</th>
              <td>
                <span>{{ season.m }}</span>
                <span
                  class="border border-main rounded text-main px-2 py-1 ml-3"
                  v-if="season.mFlg === 1"
                >昇格</span>
                <span
                  class="border border-secondary rounded text-secondary px-2 py-1 ml-3"
                  v-if="season.mFlg === -1"
                >降格</span>
              </td>
              <td>
                <span>{{ season.f }}</span>
                <span
                  class="border border-main rounded text-main px-2 py-1 ml-3"
                  v-if="season.fFlg === 1"
                >昇格</span>
                <span
                  class="border border-secondary rounded text-secondary px-2 py-1 ml-3"
                  v-if="season.fFlg === -1"
                >降格</span>
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import leagueResults from "./league_results.json";

export default {
  data: function() {
    return {
      leagueResults: leagueResults
    };
  }
};
</script>

// main/src/templates/league.tsx
import React from 'react'
import Layout from '../components/layout';
import leagueResultData from '../data/league_results.json';
import SEO from '../components/seo';

const Component: React.FC = ({ pageContext }) => {
  console.log(pageContext)
  const badge = (flg: Number) => {
    if (flg === 0) {
      return '';
    }
    return (
      <span className={`px-2 border d-inline-block ${flg === 1 && 'border-primary text-primary'} ${flg === -1 && 'border-secondary text-secondary'}`}>{flg === 1 && '昇格'}{flg === -1 && '降格'}</span>
    )
  };

  return (
    <Layout isShowPageTitle={true} pageTitle="リーグ戦" pageSubTitle="関東学生バドミントン連盟リーグ、リーグ戦の結果です">
      <SEO title="リーグ戦" />
      <table className="table table-bordered">
        <thead className="alert-secondary">
          <th>年度</th>
          <th>男子</th>
          <th>女子</th>
        </thead>
        <tbody>
          {leagueResultData.map((v, i) => (
            v.season.map((vs, i) => (
              <tr key={i}>
                <td className="text-nowrap">{`${v.year} ${vs.season === '1' ? '春' : '秋'}`}</td>
                <td><span className="pr-2">{vs.m}</span>{badge(vs.mFlg)}</td>
                <td><span className="pr-2">{vs.f}</span>{badge(vs.fFlg)}</td>
              </tr>
            ))
          ))}
        </tbody>
      </table>
    </Layout>
  )
}

export default Component
