// src/pages/results/league/Index.tsx
import React from 'react';
import LeagueResult from '../../../models/LeagueResult/LeagueResult';

const leagueResultData = LeagueResult.getData();

export default () => {
  return (
    <div>
      <h1 className="title-main">関東学生バドミントン連盟リーグ</h1>
      <div className="row justify-content-center">
        <div className="table-responsive col-md-9">
          <table className="table table-bordered">
            <thead className="bg-light">
              <tr>
                <th className="font-weight-normal" colSpan={2}>期</th>
                <th className="font-weight-normal">男子</th>
                <th className="font-weight-normal">女子</th>
              </tr>
            </thead>
            <tbody>
              {
                leagueResultData.map(() => {
                  return ( <div>aaa</div> );
                })
              }
              <tr>
                <th className="font-weight-normal bg-light align-middle">a</th>
                <th className="font-weight-normal bg-light">season</th>
                <td>
                  <span className="text-nowrap">
                    <span className="mr-2">season</span>
                    <span></span>
                  </span>
                </td>
                <td>
                  <span className="text-nowrap">
                    <span className="mr-2">season.f</span>
                    <span></span>
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// front/src/pages/results/league/Index.vue
<template>
  <div>
    <h1 class="title-main">関東学生バドミントン連盟リーグ</h1>
    <div class="row justify-content-center">
      <div class="table-responsive col-md-9">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <th class="font-weight-normal" colspan="2">期</th>
              <th class="font-weight-normal">男子</th>
              <th class="font-weight-normal">女子</th>
            </tr>
          </thead>
          <tbody>
            <template v-for="(year, i) in leagueResults">
              <tr v-for="(season, j) in year.season" :key="i + '-' + j">
                <th
                  class="font-weight-normal bg-light align-middle"
                  v-if="j === 0"
                  :rowspan="year.season.length"
                >{{ year.year }}</th>
                <th class="font-weight-normal bg-light">{{ season.season }}</th>
                <td>
                  <span class="text-nowrap">
                    <span v-if="season.detailIdM === null" class="mr-2">{{ season.m }}</span>
                    <router-link v-else class="mr-2" :to="'/results/league/' + season.detailIdM">{{ season.m }}</router-link>
                    <span>
                      <cmp-badge :flg="season.mFlg" />
                    </span>
                  </span>
                </td>
                <td>
                  <span class="text-nowrap">
                    <span v-if="season.detailIdF === null" class="mr-2">{{ season.f }}</span>
                    <router-link v-else class="mr-2" :to="'/results/league/' + season.detailIdF">{{ season.f }}</router-link>
                    <span>
                      <cmp-badge :flg="season.fFlg" />
                    </span>
                  </span>
                </td>
              </tr>
            </template>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import leagueResults from "./league_results.json";
import CmpBadge from "./CmpBadge";

export default {
  data: function() {
    return {
      leagueResults: leagueResults
    };
  },
  components: {
    "cmp-badge": CmpBadge
  }
};
</script>
