// src/pages/mizutori/index.tsx
import React, { useEffect } from 'react';
import mizutoriAuthService from '../../services/mizutoriAuthService';
import Router from 'next/router';

import obMessages from '../../data/ob_messages.json';
import Layout from '../../components/layout';
import storageService from '../../services/storageService';

const Component: React.FC = props => {
  useEffect(() => {
    if (!mizutoriAuthService.isLogin()) {
      Router.push('/mizutori/login');
    };
  }, []);

  const clickLink = async (filePath: string) => {
    const url = await storageService.getDownloadUrl(filePath);
    if (window.open(url, "_blank")) {
    } else {
      window.location.href = url;
    }
  }

  return (
    <Layout isShowPageTitle={true} pageTitle="みずとり会" pageSubTitle="みずとり会のページです。">
      {obMessages.map((v, i) => (
        <div key={i}>
          <h2 className="hub-h2" key={i}>{v.year} 年</h2>
          <div className="mb-3">
            {v.files.map((vFile, i) => (
              <a className="mr-2 v-inline-block" href="#" key={i} onClick={e => { clickLink(`ob-messages/obmessage_${vFile.id}.pdf`) }}>{vFile.title}</a>
            ))}
          </div>
        </div>
      ))}
    </Layout>
  );
};


export default Component;

// app/src/pages/mizutori/Index.vue
<template>
  <div>
    <h1 class="mb-5">みずとり会のページ</h1>
    <div class="row mb-3">
      <div class="col-md-3">
        <button class="btn btn-block btn-outline-secondary" @click="clickBtnLogout()">ログアウト</button>
      </div>
    </div>
    <div class="card mb-3" v-for="(year, i) in data" :key="i">
      <div class="card-header alert-main">{{ year.year }} 年度</div>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-2 col-md-3 col-sm-4 col-6 py-1" v-for="(month, j) in year.files" :key="j">
            <button class="btn btn-block btn-outline-main" @click="clickBtn(month.id)">{{ month.title }}</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import data from './ob-messages.json'
import obmessages from '@/firebase/obmessages'
import mizutoriAuth from '@/firebase/mizutori-auth'

export default {
  data: function() {
    return {
      data: data
    };
  },
  methods: {
    clickBtn: async function (id) {
      window.open(await obmessages.getDownloadURL(id))
    },
    clickBtnLogout: async function () {
      await mizutoriAuth.logout()
      this.$router.push('/mizutori/login')
    }
  }
};
</script>
