// src/App.tsx
import React from 'react';
import { BrowserRouter } from 'react-router-dom';

import Router from './Router';
import Navbar from './components/Navbar';

const App: React.FC = () => {
  return (
    <BrowserRouter>
      <header>
        <Navbar />
      </header>
      <main className="container">
        <Router />
      </main>
    </BrowserRouter>
  );
}

export default App;

// app/src/App.vue
<template>
  <body>
    <header>
      <cmp-navbar />
    </header>
    <main>
      <div class="container py-5">
        <router-view/>
      </div>
    </main>
    <footer>
      <cmp-footer></cmp-footer>
    </footer>
  </body>
</template>

<script>
import cmpNavbar from '@/components/Navbar'
import cmpFooter from '@/components/Footer'

export default {
  components: {
    'cmp-navbar': cmpNavbar,
    'cmp-footer': cmpFooter
  }
}
</script>
