// main/src/components/navbar.tsx
import { Link } from "gatsby"
import React from "react"

const menuArray = [
  {
    text: "部活情報",
    path: "/about",
  },
  {
    text: "部員情報",
    path: "/member-intro",
  },
  {
    text: "大会結果",
    path: "/result",
  },
  {
    text: "三多摩大会",
    path: "/santama",
  },
  {
    text: "掲示板",
    path: "/bbs",
  },
]

const Component: React.FC = () => {

  const [isActiveMenu, setIsActiveMeun] = React.useState(false);
  const handleToggleMenu = () => {
    setIsActiveMeun(!isActiveMenu);
  };

  return (
    <nav className="navbar navbar-expand-lg bg-main navbar-dark">
      <div className="container">
        <Link to="/" className="navbar-brand" style={{lineHeight: 1.3}}>一橋大学<br/>バドミントン部</Link>
        <button className="navbar-toggler border-0" type="button" onClick={handleToggleMenu}>
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className={`navbar-collapse collapse ${isActiveMenu ? 'show' : ''}`}>
          <ul className="navbar-nav ml-auto">
            {menuArray.map((menu, i) => (
              <li className="nav-item" key={i}>
                <Link to={menu.path} className="nav-link" onClick={handleToggleMenu}>{menu.text}</Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </nav>
  );
}

export default Component

// src/components/Navbar.vue
<template>
  <b-navbar toggleable="lg" type="light" variant="transparent" class="border-bottom border-secondary">
    <b-navbar-brand to="/">一橋大学<br/>バドミントン部</b-navbar-brand>
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav class="ml-auto">
        <b-nav-item to="/about">部活情報</b-nav-item>
        <b-nav-item to="/members">部員情報</b-nav-item>
        <b-nav-item to="/results">大会結果</b-nav-item>
        <b-nav-item to="/santama">三多摩大会</b-nav-item>
        <b-nav-item to="/mizutori/login">みずとり会</b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>
